exp_name: debug
exp_type: zmumu

data:
 data_path: data/
 file_0j: zmumu_0j_250M.npy
 file_1j: zmumu_1j_250M.npy
 file_2j: zmumu_2j_250M.npy
 file_3j: zmumu_3j_250M.npy
 file_4j: zmumu_4j_250M.npy
 file_5j: zmumu_5j_250M.npy
 n_jets_list: [5]
 channels: [0,1,2,4,5,6,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27]
 virtual_components:
 - - 0
 - 1

prep_gen:
 virtual: False
 phi_rel: True
 eta_rel: False
 gaussianize: true
 pt_cut: [0, 0, 20, 20, 20, 20, 20]
 standardize: true
 final_arcsinh: []

discformer:
 iterations: 1

prep_cls:
 virtual:
  use: true
  channels: null
  components: null
 delta_r:
  use: true
  invert: false
 delta_phi:
  use: true
 delta_eta:
  use: true

sampling:
 nsamples: 10000

defaults:
 - default